import { defineConfig, devices } from "@playwright/test";

// Playwright runs against the Vite preview server (production build).
// Tests live under e2e/ and exercise the file-picker flow with the
// bundled replays/sample/... directory; that path is the only real
// fixture we can rely on cross-machine (it's regenerated by
// `just runner::record-sample-replay`, see CLAUDE.md). Any test that
// needs a custom replay structure should synthesise it under a tmpdir
// rather than mutating the sample.
//
// We use chromium-headless-shell only — the viewer is plain DOM /
// vanilla TS, and browser-specific assertions (CSS quirks, audio,
// WebGL, …) aren't on our test surface. Firefox / WebKit can be
// added if a real cross-browser issue surfaces.
export default defineConfig({
  testDir: "./e2e",
  fullyParallel: false,
  forbidOnly: !!process.env["CI"],
  retries: process.env["CI"] ? 2 : 0,
  workers: process.env["CI"] ? 1 : undefined,
  reporter: process.env["CI"] ? "github" : "list",
  use: {
    baseURL: "http://127.0.0.1:4173",
    trace: "on-first-retry",
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
  ],
  webServer: {
    // `vite build && vite preview` so we exercise the same bundle
    // that ships, not the dev-mode HMR wrapper. The dev server adds
    // a websocket + source maps that aren't load-bearing for these
    // tests and slow CI for no benefit.
    command: "pnpm build && pnpm exec vite preview --port 4173 --strictPort --host 127.0.0.1",
    url: "http://127.0.0.1:4173",
    reuseExistingServer: !process.env["CI"],
    timeout: 60_000,
  },
});
