using System.Collections;
using System.Reflection;
using System.Text;
using Sts2Headless.Runtime;

namespace Sts2Headless;

// Emits src/Sts2Headless.Protocol/CardId.g.cs from the booted sts2.dll's
// ModelDb.AllCards enumeration (577+ cards on the pinned game version).
// Output is checked in — same pattern as protocol/openrpc.json — and
// CardMechanicsCoverageTests asserts the file on disk still matches the
// generator's output, so a PR that bumps the game pin without
// regenerating the enum fails CI rather than landing silently.
//
// Naming convention:
//   wire (the engine's Id.Entry):  STRIKE_IRONCLAD, SWORD_BOOMERANG
//   C# enum value (PascalCase):    StrikeIronclad, SwordBoomerang
//
// The wire ↔ enum mapping is encoded via [JsonStringEnumMemberName] on
// each member so the JSON serialiser round-trips correctly, AND via a
// generated CardIdNames.FromWire(string) dictionary so the binding
// layer can map sts2's runtime Id.Entry strings into the enum without
// reflecting over attributes on every read.
internal static class GenerateCardIdsCommand
{
    public static int Run(string vendorDir, string repoRoot)
    {
        var preamble = RuntimeBootstrap.Run(vendorDir);
        if (preamble.SetupError is not null)
        {
            Console.Error.WriteLine($"generate-card-ids: bootstrap setup failed — {preamble.SetupError}");
            return 1;
        }

        var steps = BootstrapSequence.Apply(preamble.Sts2!);
        var failed = steps.Where(s => !s.Ok).ToList();
        if (failed.Count > 0)
        {
            Console.Error.WriteLine("generate-card-ids: bootstrap step failures —");
            foreach (var f in failed) Console.Error.WriteLine($"  [FAIL] {f.Label}: {f.Detail}");
            return 1;
        }

        var sts2 = preamble.Sts2!;
        var modelDbType = sts2.GetType("MegaCrit.Sts2.Core.Models.ModelDb")
            ?? throw new InvalidOperationException("ModelDb type not found in sts2.dll");
        var allCards = modelDbType.GetProperty("AllCards", BindingFlags.Public | BindingFlags.Static)
            ?? throw new InvalidOperationException("ModelDb.AllCards property not found — game version drift?");

        if (allCards.GetValue(null) is not IEnumerable cardModels)
        {
            Console.Error.WriteLine("generate-card-ids: ModelDb.AllCards did not return an IEnumerable.");
            return 1;
        }

        var ids = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var m in cardModels)
        {
            if (m is null) continue;
            var idProp = m.GetType().GetProperty("Id", BindingFlags.Public | BindingFlags.Instance);
            if (idProp?.GetValue(m) is not object idObj) continue;
            var entryProp = idObj.GetType().GetProperty("Entry", BindingFlags.Public | BindingFlags.Instance);
            if (entryProp?.GetValue(idObj) is not string entry) continue;
            ids.Add(entry);
        }
        if (ids.Count == 0)
        {
            Console.Error.WriteLine("generate-card-ids: enumerated 0 cards — refusing to emit empty CardId.g.cs.");
            return 1;
        }

        var outPath = Path.Combine(repoRoot, "src", "Sts2Headless.Protocol", "CardId.g.cs");
        var source = Emit(ids);
        File.WriteAllText(outPath, source);
        Console.WriteLine($"wrote {Path.GetRelativePath(repoRoot, outPath)}  ({ids.Count} cards)");
        return 0;
    }

    // Convert SCREAMING_SNAKE_CASE to PascalCase. Each underscore-separated
    // word becomes Title-cased; consecutive uppercase letters collapse
    // (e.g. ALL_FOR_ONE → AllForOne). Pure ASCII — card IDs in sts2 don't
    // contain unicode.
    private static string ToPascalCase(string snake)
    {
        var sb = new StringBuilder(snake.Length);
        var atWordStart = true;
        foreach (var ch in snake)
        {
            if (ch == '_') { atWordStart = true; continue; }
            sb.Append(atWordStart ? char.ToUpperInvariant(ch) : char.ToLowerInvariant(ch));
            atWordStart = false;
        }
        return sb.ToString();
    }

    private static string Emit(SortedSet<string> wireIds)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Source: generated by `just generate-card-ids` (Sts2Headless --generate-card-ids).");
        sb.AppendLine("//   Sourced from ModelDb.AllCards in the pinned vendor/sts2.dll.");
        sb.AppendLine("//   Do not edit by hand — re-run the generator after bumping the game pin.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Sts2Headless.Protocol;");
        sb.AppendLine();
        sb.AppendLine("namespace Sts2Headless.Protocol.Methods;");
        sb.AppendLine();
        sb.AppendLine("// Every card sts2 ships, as discovered by ModelDb.AllCards on the");
        sb.AppendLine("// pinned game version. Unknown is the sentinel for card IDs that");
        sb.AppendLine("// post-date the pinned enum (e.g. a future game patch the runtime");
        sb.AppendLine("// is talking to ships new cards before the pin is bumped). The");
        sb.AppendLine("// binding layer maps sts2's runtime Id.Entry strings to this enum");
        sb.AppendLine("// via CardIdNames.FromWire; unknown strings collapse to Unknown.");
        sb.AppendLine("[OpaqueWireString]");
        sb.AppendLine("[JsonConverter(typeof(JsonStringEnumConverter<CardId>))]");
        sb.AppendLine("public enum CardId");
        sb.AppendLine("{");
        sb.AppendLine("    [JsonStringEnumMemberName(\"UNKNOWN\")] Unknown,");
        foreach (var wire in wireIds)
        {
            var pascal = ToPascalCase(wire);
            sb.AppendLine($"    [JsonStringEnumMemberName(\"{wire}\")] {pascal},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Static wire-name ↔ enum lookups. The binding layer reads sts2's");
        sb.AppendLine("// Id.Entry string and needs the inverse of the JsonStringEnumMember-");
        sb.AppendLine("// Name attribute; emitting an explicit dictionary avoids reflecting");
        sb.AppendLine("// over enum members on every read and keeps the lookup O(1).");
        sb.AppendLine("public static class CardIdNames");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly System.Collections.Generic.Dictionary<string, CardId> _fromWire = new(System.StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var wire in wireIds)
        {
            var pascal = ToPascalCase(wire);
            sb.AppendLine($"        [\"{wire}\"] = CardId.{pascal},");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    // Map a sts2 runtime card-id string (the engine's Id.Entry) into");
        sb.AppendLine("    // the CardId enum. Unrecognised strings collapse to Unknown so");
        sb.AppendLine("    // the wire never carries a free-form id we can't account for.");
        sb.AppendLine("    public static CardId FromWire(string wireName) =>");
        sb.AppendLine("        _fromWire.TryGetValue(wireName, out var id) ? id : CardId.Unknown;");
        sb.AppendLine();
        sb.AppendLine("    // Snapshot of every catalogued wire id, in the order they appear");
        sb.AppendLine("    // in the enum. Coverage tests use this to assert that every");
        sb.AppendLine("    // shipped card has either a Mechanics entry or an explicit");
        sb.AppendLine("    // NotYetModelled opt-out — without re-walking the assembly.");
        sb.AppendLine("    public static System.Collections.Generic.IReadOnlyCollection<string> AllWireNames => _fromWire.Keys;");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
