import type { Locator, Page } from "@playwright/test";
import { readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

// Resolves the directory holding the bundled vendor sample run. The
// rest of the e2e suite assumes this directory exists; if a future
// change splits the sample across versions we'll need to make this
// configurable. Today there's a single `<root>/v0.103.2/<run-id>/`
// dir under vendor/replays/sample.
//
// Layout it expects (regenerated by `just record-sample-replay`):
//   vendor/replays/sample/<game-version>/<run-id>/
//     manifest.json
//     combats/*.mcr
//     combats/*.mcr.timeline.json
//     run.json
export function locateSampleRunDir(): string {
  const repoRoot = resolve(HERE, "..", "..", "..");
  const versionsRoot = join(repoRoot, "vendor", "replays", "sample");
  const versions = readdirSync(versionsRoot).filter((d) => d.startsWith("v"));
  if (versions.length === 0) throw new Error(`no game-version dirs under ${versionsRoot} — run \`just record-sample-replay\``);
  const versionDir = join(versionsRoot, versions[0]!);
  const runs = readdirSync(versionDir).filter((d) => statSync(join(versionDir, d)).isDirectory());
  if (runs.length === 0) throw new Error(`no run dirs under ${versionDir}`);
  return join(versionDir, runs[0]!);
}

// Picks a directory via the `<input webkitdirectory>` element. Playwright's
// setInputFiles understands webkitdirectory inputs when given a directory
// path, and walks it server-side to produce the same FileList the user
// would get from the file picker.
//
// Waits for the floor list to actually render before returning — the
// page's "change" handler is async (reads every file, parses JSON,
// builds the session) and tests that fire assertions immediately after
// setInputFiles can race ahead of the first paint and see zero rows.
export async function pickRunDirectory(page: Page, runDir: string): Promise<void> {
  const input: Locator = page.locator("#directory-input");
  await input.setInputFiles(runDir);
  // Either the full-run view renders (.viewer-floor-row) or the
  // manifest-only fallback does (.viewer-combat-row). One of the two
  // must be visible after a successful load. Errors surface via
  // .errors instead — also fail fast there.
  await page.waitForFunction(
    () => {
      const errors = document.getElementById("errors");
      if (errors && errors.textContent && errors.textContent.length > 0) return true;
      return (
        document.querySelectorAll(".viewer-floor-row").length > 0 ||
        document.querySelectorAll(".viewer-combat-row").length > 0
      );
    },
    undefined,
    { timeout: 5000 },
  );
}
