# generated by datamodel-codegen:
#   filename:  headless-in-the-spire-openrpc.json

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class BadgeRarity(Enum):
    unknown = "Unknown"
    bronze = "bronze"
    silver = "silver"
    gold = "gold"


class CardRewardOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str
    cost: int


class CardSpec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    card_id: Annotated[str, Field(alias="cardId")]
    upgrade_level: Annotated[int | None, Field(alias="upgradeLevel")] = 0


class Character(Enum):
    ironclad = "ironclad"
    silent = "silent"
    defect = "defect"
    watcher = "watcher"
    regent = "regent"
    necrobinder = "necrobinder"


class DebugGiveRelicParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    relic_id: Annotated[str, Field(alias="relicId")]


class DebugGiveRelicResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    relic_id: Annotated[str, Field(alias="relicId")]
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    gold: int
    deck_size: Annotated[int, Field(alias="deckSize")]


class DebugKillAllEnemiesParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class DebugKillAllEnemiesResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    killed: int
    combat_ended: Annotated[bool, Field(alias="combatEnded")]


class DebugReadDeckParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class DebugReadDeckResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    deck_size: Annotated[int, Field(alias="deckSize")]
    cards: list[CardSpec]


class DebugReplaceDeckParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    cards: list[CardSpec]


class DebugReplaceDeckResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    deck_size: Annotated[int, Field(alias="deckSize")]
    card_ids: Annotated[list[str], Field(alias="cardIds")]


class DebugSetHpParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    hp: int
    max_hp: Annotated[int | None, Field(alias="maxHp")] = None


class DebugSetHpResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]


class EventOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    text_key: Annotated[str | None, Field(alias="textKey")] = None
    is_locked: Annotated[bool, Field(alias="isLocked")]


class GameMode(Enum):
    unknown = "Unknown"
    standard = "standard"
    daily = "daily"
    custom = "custom"
    endless = "endless"


class HistoryBadge(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(alias="Id")]
    rarity: Annotated[BadgeRarity, Field(alias="Rarity")]


class HistoryCardRef(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(alias="Id")]
    floor_added_to_deck: Annotated[int | None, Field(alias="FloorAddedToDeck")]


class HistoryCardTransformation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    original_card: Annotated[HistoryCardRef, Field(alias="OriginalCard")]
    final_card: Annotated[HistoryCardRef, Field(alias="FinalCard")]


class HistoryLocalisationKey(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[str, Field(alias="Key")]
    table: Annotated[str, Field(alias="Table")]


class HistoryOwnedPotion(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(alias="Id")]
    slot_index: Annotated[int, Field(alias="SlotIndex")]


class HistoryRelicChoice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    choice: Annotated[str | None, Field(alias="Choice")]
    was_picked: Annotated[bool, Field(alias="WasPicked")]


class HostPingResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    game_version: Annotated[str | None, Field(alias="gameVersion")] = None
    game_sha256: Annotated[str | None, Field(alias="gameSha256")] = None


class IntentKind(Enum):
    unknown = "Unknown"
    attack = "Attack"
    defend = "Defend"
    buff = "Buff"
    debuff = "Debuff"
    sleep = "Sleep"
    stun = "Stun"
    escape = "Escape"
    magic = "Magic"
    attack_defend = "AttackDefend"
    attack_buff = "AttackBuff"
    attack_debuff = "AttackDebuff"
    strong_debuff = "StrongDebuff"


class MapNodeType(Enum):
    unknown = "Unknown"
    monster = "Monster"
    elite = "Elite"
    event = "Event"
    rest_site = "RestSite"
    treasure = "Treasure"
    merchant = "Merchant"
    boss = "Boss"


class MerchantKind(Enum):
    unknown = "unknown"
    card = "card"
    relic = "relic"
    potion = "potion"
    card_removal = "card_removal"


class PlatformType(Enum):
    unknown = "Unknown"
    none = "none"
    steam = "steam"
    gog = "gog"
    epic = "epic"
    switch = "switch"


class Power(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    amount: int


class Relic(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str


class RestSiteOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    option_id: Annotated[str, Field(alias="optionId")]
    is_enabled: Annotated[bool, Field(alias="isEnabled")]


class RewardKind(Enum):
    unknown = "unknown"
    card = "card"
    gold = "gold"
    relic = "relic"
    potion = "potion"


class RewardOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    kind: RewardKind
    can_skip: Annotated[bool, Field(alias="canSkip")]
    gold_amount: Annotated[int | None, Field(alias="goldAmount")] = None
    potion_id: Annotated[str | None, Field(alias="potionId")] = None
    relic_id: Annotated[str | None, Field(alias="relicId")] = None
    cards: list[CardRewardOption] | None = None


class RewardsState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    available: list[RewardOption]


class RoomType(Enum):
    unknown = "Unknown"
    map_room = "MapRoom"
    event_room = "EventRoom"
    combat_room = "CombatRoom"
    rest_site_room = "RestSiteRoom"
    merchant_room = "MerchantRoom"
    treasure_room = "TreasureRoom"
    boss_room = "BossRoom"


class RunBuyMerchantItemParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    item_index: Annotated[int, Field(alias="itemIndex")]


class RunHistoryMapPointType(Enum):
    unknown = "Unknown"
    ancient = "ancient"
    boss = "boss"
    elite = "elite"
    monster = "monster"
    rest_site = "rest_site"
    shop = "shop"
    treasure = "treasure"
    unknown_1 = "unknown"


class RunHistoryModifier(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str | None, Field(alias="Id")]


class RunHistoryPlayer(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[int, Field(alias="Id")]
    character: Annotated[str, Field(alias="Character")]
    max_potion_slot_count: Annotated[int, Field(alias="MaxPotionSlotCount")]
    deck: Annotated[list[HistoryCardRef] | None, Field(alias="Deck")]
    relics: Annotated[list[HistoryCardRef] | None, Field(alias="Relics")]
    potions: Annotated[list[HistoryOwnedPotion] | None, Field(alias="Potions")]
    badges: Annotated[list[HistoryBadge] | None, Field(alias="Badges")]


class RunHistoryRoomType(Enum):
    unknown = "Unknown"
    boss = "boss"
    elite = "elite"
    event = "event"
    monster = "monster"
    rest_site = "rest_site"
    shop = "shop"
    treasure = "treasure"


class RunNewParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    character: Character | None = None
    seed: int | None = None
    with_neow: Annotated[bool | None, Field(alias="withNeow")] = None
    ascension: int | None = None
    modifiers: list[str] | None = None


class RunPlayCardParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    card_index: Annotated[int, Field(alias="cardIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None
    card_select_indices: Annotated[
        list[list[int]] | None, Field(alias="cardSelectIndices")
    ] = None


class RunSelectEventOptionParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    option_index: Annotated[int, Field(alias="optionIndex")]


class RunSelectMapNodeParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    col: int
    row: int


class RunSelectRestSiteOptionParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    option_index: Annotated[int, Field(alias="optionIndex")]
    card_select_indices: Annotated[
        list[list[int]] | None, Field(alias="cardSelectIndices")
    ] = None


class RunSelectRewardParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    reward_index: Annotated[int, Field(alias="rewardIndex")]
    card_index: Annotated[int | None, Field(alias="cardIndex")] = None


class RunSkipRewardParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    reward_index: Annotated[int, Field(alias="rewardIndex")]


class RunUsePotionParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    potion_index: Annotated[int, Field(alias="potionIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None


class TargetType(Enum):
    unknown = "Unknown"
    none = "None"
    any_enemy = "AnyEnemy"
    all_enemies = "AllEnemies"
    self = "Self"
    any_ally = "AnyAlly"
    all_allies = "AllAllies"
    caster = "Caster"


class TriggerKind(Enum):
    unknown = "unknown"
    relic = "relic"
    card = "card"
    monster = "monster"
    potion = "potion"
    power = "power"


class Card(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str
    cost: int
    can_play: Annotated[bool, Field(alias="canPlay")]
    target_type: Annotated[TargetType, Field(alias="targetType")]


class HistoryChoiceEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    text_key: Annotated[str, Field(alias="TextKey")]
    title: Annotated[HistoryLocalisationKey, Field(alias="Title")]
    was_chosen: Annotated[bool, Field(alias="WasChosen")]


class HistoryEventChoice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: Annotated[HistoryLocalisationKey, Field(alias="Title")]


class Intent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: IntentKind
    damage: int | None = None
    hits: int | None = None
    block: int | None = None


class MapNode(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    col: int
    row: int
    type: MapNodeType


class MapPointPlayerStats(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    player_id: Annotated[int, Field(alias="PlayerId")]
    ancient_choice: Annotated[
        list[HistoryChoiceEntry] | None, Field(alias="AncientChoice")
    ]
    cards_gained: Annotated[list[HistoryCardRef] | None, Field(alias="CardsGained")]
    cards_removed: Annotated[list[HistoryCardRef] | None, Field(alias="CardsRemoved")]
    cards_transformed: Annotated[
        list[HistoryCardTransformation] | None, Field(alias="CardsTransformed")
    ]
    event_choices: Annotated[
        list[HistoryEventChoice] | None, Field(alias="EventChoices")
    ]
    relic_choices: Annotated[
        list[HistoryRelicChoice] | None, Field(alias="RelicChoices")
    ]
    current_gold: Annotated[int, Field(alias="CurrentGold")]
    current_hp: Annotated[int, Field(alias="CurrentHp")]
    damage_taken: Annotated[int, Field(alias="DamageTaken")]
    gold_gained: Annotated[int, Field(alias="GoldGained")]
    gold_lost: Annotated[int, Field(alias="GoldLost")]
    gold_spent: Annotated[int, Field(alias="GoldSpent")]
    gold_stolen: Annotated[int, Field(alias="GoldStolen")]
    hp_healed: Annotated[int, Field(alias="HpHealed")]
    max_hp: Annotated[int, Field(alias="MaxHp")]
    max_hp_gained: Annotated[int, Field(alias="MaxHpGained")]
    max_hp_lost: Annotated[int, Field(alias="MaxHpLost")]


class MapPointRoom(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    room_type: Annotated[RunHistoryRoomType, Field(alias="RoomType")]
    model_id: Annotated[str | None, Field(alias="ModelId")]
    turns_taken: Annotated[int, Field(alias="TurnsTaken")]


class MerchantItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    kind: MerchantKind
    cost: int
    is_stocked: Annotated[bool, Field(alias="isStocked")]
    is_affordable: Annotated[bool, Field(alias="isAffordable")]
    card_id: Annotated[str | None, Field(alias="cardId")] = None
    relic_id: Annotated[str | None, Field(alias="relicId")] = None
    potion_id: Annotated[str | None, Field(alias="potionId")] = None


class OwnedPotion(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str
    target_type: Annotated[TargetType, Field(alias="targetType")]
    can_use: Annotated[bool, Field(alias="canUse")]


class TriggerEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: TriggerKind
    source: str
    hook: str


class Enemy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    monster_id: Annotated[str | None, Field(alias="monsterId")] = None
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    block: int
    intends_attack: Annotated[bool, Field(alias="intendsAttack")]
    intents: list[Intent]
    powers: list[Power]


class MapPointHistoryEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    map_point_type: Annotated[RunHistoryMapPointType, Field(alias="MapPointType")]
    rooms: Annotated[list[MapPointRoom] | None, Field(alias="Rooms")]
    player_stats: Annotated[
        list[MapPointPlayerStats] | None, Field(alias="PlayerStats")
    ]


class RunHistoryDocument(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    schema_version: Annotated[int, Field(alias="SchemaVersion")]
    ascension: Annotated[int, Field(alias="Ascension")]
    build_id: Annotated[str, Field(alias="BuildId")]
    game_mode: Annotated[GameMode, Field(alias="GameMode")]
    killed_by_encounter: Annotated[str, Field(alias="KilledByEncounter")]
    killed_by_event: Annotated[str, Field(alias="KilledByEvent")]
    map_point_history: Annotated[
        list[list[MapPointHistoryEntry]], Field(alias="MapPointHistory")
    ]
    modifiers: Annotated[list[RunHistoryModifier], Field(alias="Modifiers")]
    platform_type: Annotated[PlatformType, Field(alias="PlatformType")]
    players: Annotated[list[RunHistoryPlayer], Field(alias="Players")]
    run_time: Annotated[int, Field(alias="RunTime")]
    seed: Annotated[str, Field(alias="Seed")]
    start_time: Annotated[int, Field(alias="StartTime")]
    was_abandoned: Annotated[bool, Field(alias="WasAbandoned")]
    win: Annotated[bool, Field(alias="Win")]


class CombatState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    round: int
    energy: int
    max_energy: Annotated[int, Field(alias="maxEnergy")]
    player_block: Annotated[int, Field(alias="playerBlock")]
    is_play_phase: Annotated[bool, Field(alias="isPlayPhase")]
    is_in_progress: Annotated[bool, Field(alias="isInProgress")]
    draw_pile_count: Annotated[int, Field(alias="drawPileCount")]
    discard_pile_count: Annotated[int, Field(alias="discardPileCount")]
    hand: list[Card]
    enemies: list[Enemy]
    player_powers: Annotated[list[Power], Field(alias="playerPowers")]


class RunBuyMerchantItemResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    item_index: Annotated[int, Field(alias="itemIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunEndTurnResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunEnterNextActResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunLeaveMerchantRoomResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunLeaveTreasureRoomResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunNewResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    character: Character
    seed: int
    player_type: Annotated[str, Field(alias="playerType")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]
    modifiers: list[str]


class RunPlayCardResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    card_index: Annotated[int, Field(alias="cardIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunProceedEventResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectEventOptionResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    option_index: Annotated[int, Field(alias="optionIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectMapNodeResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    col: int
    row: int
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectRestSiteOptionResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    option_index: Annotated[int, Field(alias="optionIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectRewardResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    reward_index: Annotated[int, Field(alias="rewardIndex")]
    card_index: Annotated[int | None, Field(alias="cardIndex")] = None
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSkipRewardResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    reward_index: Annotated[int, Field(alias="rewardIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunStateResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    character: Character | None = None
    seed: int
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    gold: int
    deck_size: Annotated[int, Field(alias="deckSize")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]
    triggered_since_prev: Annotated[
        list[TriggerEvent], Field(alias="triggeredSincePrev")
    ]
    triggered_dropped: Annotated[int, Field(alias="triggeredDropped")]


class RunUsePotionResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    potion_index: Annotated[int, Field(alias="potionIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    current_act_index: Annotated[int, Field(alias="currentActIndex")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    is_victory: Annotated[bool, Field(alias="isVictory")]
    is_dead: Annotated[bool, Field(alias="isDead")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]
