# generated by datamodel-codegen:
#   filename:  headless-in-the-spire-openrpc.json

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class CardRewardOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str
    cost: int


class Character(Enum):
    ironclad = "ironclad"
    silent = "silent"
    defect = "defect"
    watcher = "watcher"
    regent = "regent"
    necrobinder = "necrobinder"


class DebugGiveRelicParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    relic_id: Annotated[str, Field(alias="relicId")]


class DebugGiveRelicResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    relic_id: Annotated[str, Field(alias="relicId")]
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    gold: int
    deck_size: Annotated[int, Field(alias="deckSize")]


class DebugSetHpParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    hp: int
    max_hp: Annotated[int | None, Field(alias="maxHp")] = None


class DebugSetHpResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]


class EventOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    text_key: Annotated[str | None, Field(alias="textKey")] = None
    is_locked: Annotated[bool, Field(alias="isLocked")]


class HostPingResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    game_version: Annotated[str | None, Field(alias="gameVersion")] = None
    game_sha256: Annotated[str | None, Field(alias="gameSha256")] = None


class IntentKind(Enum):
    unknown = "Unknown"
    attack = "Attack"
    defend = "Defend"
    buff = "Buff"
    debuff = "Debuff"
    sleep = "Sleep"
    stun = "Stun"
    escape = "Escape"
    magic = "Magic"
    attack_defend = "AttackDefend"
    attack_buff = "AttackBuff"
    attack_debuff = "AttackDebuff"
    strong_debuff = "StrongDebuff"


class MapNodeType(Enum):
    unknown = "Unknown"
    monster = "Monster"
    elite = "Elite"
    event = "Event"
    rest_site = "RestSite"
    treasure = "Treasure"
    merchant = "Merchant"
    boss = "Boss"


class MerchantKind(Enum):
    unknown = "unknown"
    card = "card"
    relic = "relic"
    potion = "potion"
    card_removal = "card_removal"


class Power(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    amount: int


class Relic(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str


class RestSiteOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    option_id: Annotated[str, Field(alias="optionId")]
    is_enabled: Annotated[bool, Field(alias="isEnabled")]


class RewardKind(Enum):
    unknown = "unknown"
    card = "card"
    gold = "gold"
    relic = "relic"
    potion = "potion"


class RewardOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    kind: RewardKind
    can_skip: Annotated[bool, Field(alias="canSkip")]
    gold_amount: Annotated[int | None, Field(alias="goldAmount")] = None
    potion_id: Annotated[str | None, Field(alias="potionId")] = None
    relic_id: Annotated[str | None, Field(alias="relicId")] = None
    cards: list[CardRewardOption] | None = None


class RewardsState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    available: list[RewardOption]


class RoomType(Enum):
    unknown = "Unknown"
    map_room = "MapRoom"
    event_room = "EventRoom"
    combat_room = "CombatRoom"
    rest_site_room = "RestSiteRoom"
    merchant_room = "MerchantRoom"
    treasure_room = "TreasureRoom"
    boss_room = "BossRoom"


class RunBuyMerchantItemParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    item_index: Annotated[int, Field(alias="itemIndex")]


class RunNewParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    character: Character | None = None
    seed: int | None = None
    with_neow: Annotated[bool | None, Field(alias="withNeow")] = None


class RunPlayCardParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    card_index: Annotated[int, Field(alias="cardIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None


class RunSelectEventOptionParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    option_index: Annotated[int, Field(alias="optionIndex")]


class RunSelectMapNodeParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    col: int
    row: int


class RunSelectRestSiteOptionParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    option_index: Annotated[int, Field(alias="optionIndex")]


class RunSelectRewardParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    reward_index: Annotated[int, Field(alias="rewardIndex")]
    card_index: Annotated[int | None, Field(alias="cardIndex")] = None


class RunSkipRewardParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    reward_index: Annotated[int, Field(alias="rewardIndex")]


class RunUsePotionParams(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    potion_index: Annotated[int, Field(alias="potionIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None


class TargetType(Enum):
    unknown = "Unknown"
    none = "None"
    any_enemy = "AnyEnemy"
    all_enemies = "AllEnemies"
    self = "Self"
    any_ally = "AnyAlly"
    all_allies = "AllAllies"
    caster = "Caster"


class Card(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str
    cost: int
    can_play: Annotated[bool, Field(alias="canPlay")]
    target_type: Annotated[TargetType, Field(alias="targetType")]


class Intent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: IntentKind
    damage: int | None = None
    hits: int | None = None
    block: int | None = None


class MapNode(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    col: int
    row: int
    type: MapNodeType


class MerchantItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    kind: MerchantKind
    cost: int
    is_stocked: Annotated[bool, Field(alias="isStocked")]
    is_affordable: Annotated[bool, Field(alias="isAffordable")]
    card_id: Annotated[str | None, Field(alias="cardId")] = None
    relic_id: Annotated[str | None, Field(alias="relicId")] = None
    potion_id: Annotated[str | None, Field(alias="potionId")] = None


class OwnedPotion(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str
    target_type: Annotated[TargetType, Field(alias="targetType")]
    can_use: Annotated[bool, Field(alias="canUse")]


class Enemy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    monster_id: Annotated[str | None, Field(alias="monsterId")] = None
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    block: int
    intends_attack: Annotated[bool, Field(alias="intendsAttack")]
    intents: list[Intent]
    powers: list[Power]


class CombatState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    round: int
    energy: int
    max_energy: Annotated[int, Field(alias="maxEnergy")]
    player_block: Annotated[int, Field(alias="playerBlock")]
    is_play_phase: Annotated[bool, Field(alias="isPlayPhase")]
    is_in_progress: Annotated[bool, Field(alias="isInProgress")]
    draw_pile_count: Annotated[int, Field(alias="drawPileCount")]
    discard_pile_count: Annotated[int, Field(alias="discardPileCount")]
    hand: list[Card]
    enemies: list[Enemy]
    player_powers: Annotated[list[Power], Field(alias="playerPowers")]


class RunBuyMerchantItemResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    item_index: Annotated[int, Field(alias="itemIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunEndTurnResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunLeaveMerchantRoomResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunLeaveTreasureRoomResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunNewResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    character: Character
    seed: int
    player_type: Annotated[str, Field(alias="playerType")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunPlayCardResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    card_index: Annotated[int, Field(alias="cardIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectEventOptionResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    option_index: Annotated[int, Field(alias="optionIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectMapNodeResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    col: int
    row: int
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectRestSiteOptionResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    option_index: Annotated[int, Field(alias="optionIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSelectRewardResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    reward_index: Annotated[int, Field(alias="rewardIndex")]
    card_index: Annotated[int | None, Field(alias="cardIndex")] = None
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunSkipRewardResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    reward_index: Annotated[int, Field(alias="rewardIndex")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunStateResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    character: Character | None = None
    seed: int
    hp: int
    max_hp: Annotated[int, Field(alias="maxHp")]
    gold: int
    deck_size: Annotated[int, Field(alias="deckSize")]
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]


class RunUsePotionResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ok: bool
    potion_index: Annotated[int, Field(alias="potionIndex")]
    target_index: Annotated[int | None, Field(alias="targetIndex")] = None
    current_room_type: Annotated[RoomType, Field(alias="currentRoomType")]
    act_floor: Annotated[int, Field(alias="actFloor")]
    is_game_over: Annotated[bool, Field(alias="isGameOver")]
    hp: int
    available_map_nodes: Annotated[list[MapNode], Field(alias="availableMapNodes")]
    available_event_options: Annotated[
        list[EventOption], Field(alias="availableEventOptions")
    ]
    available_rest_site_options: Annotated[
        list[RestSiteOption], Field(alias="availableRestSiteOptions")
    ]
    available_merchant_items: Annotated[
        list[MerchantItem], Field(alias="availableMerchantItems")
    ]
    combat_state: Annotated[CombatState | None, Field(alias="combatState")] = None
    rewards_state: Annotated[RewardsState | None, Field(alias="rewardsState")] = None
    relics: list[Relic]
    owned_potions: Annotated[list[OwnedPotion], Field(alias="ownedPotions")]
